#![cfg_attr(not(test), warn(clippy::unwrap_used, clippy::expect_used))]

pub mod api;
#[cfg(feature = "client")]
pub mod client;
#[cfg(feature = "blocking-http")]
pub mod http;
#[cfg(feature = "blocking-http")]
pub mod remote_action;
pub mod keys;
pub mod process;
pub mod profiles;
pub mod selection;
pub mod send_payload;
pub mod shell;
pub mod theme;
pub mod timing;
pub mod types;
pub mod ws;
